### ISSUE TITLE
게시글 카테고리 축소

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/hisbee#257]
# Description

기존 카테고리를 "수업 프로젝트", "사이드 프로젝트"로 축소한다.

# Story Points:

1

**Comment by ohinhyuk** [comment]
프론트도 이슈를 관련 이슈를 생성하고 작업하였습니다.

[https://github.com/HGU-WALAB/hisbee/issues/258](https://github.com/HGU-WALAB/hisbee/issues/258)
이슈 번호 #258
